# For local development
web:
  build: .
  dockerfile: Dockerfile
  links:
    - database
  ports:
    - "5000"

database:
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: apiuser
    POSTGRES_PASSWORD: password
    POSTGRES_DB: messages
  expose:
    - 5432




    
